services:
  mysql:
      image: mysql:8.0.31
      container_name: sample-mysql
      environment:
        # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: sample
        TZ: 'Asia/Tokyo'
      volumes:
        - ./.docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306
